In [3]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interactive
%matplotlib inline

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!pip install streamlit -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 55.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 64.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 22.1 MB/s eta 0:00:00
  Building wheel for validators (setup.py) ... done

In [6]:
import streamlit as sl

In [7]:

import pandas as pd
import numpy as np
import csv

In [8]:

movies=pd.read_csv("drive/MyDrive/Colab Notebooks/movie.csv")

In [9]:
movies.head(50)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",NaN,2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...","[{""iso_3166_1"": ""CZ"", ""name"": ""Czech Republic""...",2008-05-15,419651413,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.theamazingspiderman.com,1930,"[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-06-27,752215857,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The untold story begins.,The Amazing Spider-Man,6.5,6586
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.robinhoodthemovie.com/,20662,"[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,When soldier Robin happens upon the dying Robe...,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-05-12,310669540,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.thehobbit.com/,57158,"[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2013-12-11,958400000,161.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.goldencompassmovie.com/index_german...,2268,"[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,"After overhearing a shocking secret, precociou...",42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2007-12-04,372234864,113.0,"[{""iso_639_1"": ""is"", ""name"": ""\u00cdslenska""},...",Released,There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303
24,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,254,"[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2005-12-14,550000000,187.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The eighth wonder of the world.,King Kong,6.6,2337
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1997-11-18,1845034188,194.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Nothing on Earth could come between them.,Titanic,7.5,7562
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://marvel.com/captainamericapremiere,271110,"[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,"Following the events of Age of Ultron, the col...",198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-04-27,1153304495,147.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103...",Released,Divided We Fall,Captain America: Civil War,7.1,7241
27,209000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",NaN,44833,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",en,Battleship,"When mankind beams a radio signal into space, ...",64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-11,303025485,131.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Battle for Earth Begins at Sea,Battleship,5.5,2114
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-06-09,1513528810,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.skyfall-movie.com,37724,"[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,When Bond's latest assignment goes gravely wro...,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2012-10-25,1108561013,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Think on your sins.,Skyfall,6.9,7604
30,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spider-man2/,558,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 2,Peter Parker is going through a major identity...,35.149586,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-06-25,783766341,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,There's a hero in all of us.,Spider-Man 2,6.7,4321
31,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/ironman3,68721,"[{""id"": 949, ""name"": ""terrorist""}, {""id"": 5597...",en,Iron Man 3,When Tony Stark's world is torn apart by a for...,77.682080,"[{""name"": ""Marvel Studios"", ""id"": 420}]","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2013-04-18,1215439994,130.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Unleash the power behind the armor.,Iron Man 3,6.8,8806
32,200000000,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 14, ""...",http://disney.go.com/wonderland/,12155,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...",78.530105,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-03-03,1025491110,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You're invited to a very important date.,Alice in Wonderland,6.4,4645
33,210000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",NaN,36668,"[{""id"": 1852, ""name"": ""mutant""}, {""id"": 8828, ...",en,X-Men: The Last Stand,"When a cure is found to treat mutations, lines...",3.857526,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2006-05-24,459359555,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Take a Stand,X-Men: The Last Stand,6.3,3525
34,200000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,62211,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 5984,...",en,Monsters University,A look at the relationship between Mike and Su...,89.186492,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-06-20,743559607,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,School never looked this scary.,Monsters University,7.0,3528
35,150000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.transformersmovie.com/,8373,"[{""id"": 1160, ""name"": ""egypt""}, {""id"": 1670, ""...",en,Transformers: Revenge of the Fallen,Sam Witwicky leaves the Autobots behind for a ...,21.939663,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-06-19,836297228,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Revenge is coming.,Transformers: Revenge of the Fallen,6.0,3138
36,210000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.transformersmovie.com,91314,"[{""id"": 9663, ""name"": ""sequel""}, {""id"": 9951, ...",en,Transformers: Age of Extinction,"As humanity picks up the pieces, following the...",116.840296,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2014-06-25,1091405097,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,This is not war. It's extinction.,Transformers: Age of Extinction,5.8,3095

In [10]:

movies["keywords"][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [11]:

movies["tagline"][0]

'Enter the World of Pandora.'

In [12]:
movies["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [13]:
df2=pd.read_csv("drive/MyDrive/Colab Notebooks/movie_credit.csv")

In [14]:
df2.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:

df2["cast"]

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4798    [{"cast_id": 1, "character": "El Mariachi", "c...
4799    [{"cast_id": 1, "character": "Buzzy", "credit_...
4800    [{"cast_id": 8, "character": "Oliver O\u2019To...
4801    [{"cast_id": 3, "character": "Sam", "credit_id...
4802    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4803, dtype: object

In [16]:
movies=movies.merge(df2,on="title")

In [17]:

movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [18]:
import ast
def str_list(x):
  x=ast.literal_eval(x)
  l=[]
  for item in x:

    l.append(item['name'])

  return l

In [19]:
movies["cast"]=movies["cast"].apply(str_list)

In [20]:
import ast
def str2_list(x):
  x=ast.literal_eval(x)
  l=[]
  for item in x:
    if item['job']=="Director":
      l.append(item['name'])

  return l

In [21]:
movies["crew"]=movies["crew"].apply(str2_list)

In [22]:
movies["cast"]

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4809, dtype: object

In [23]:
movies["crew"]

0                                [James Cameron]
1                               [Gore Verbinski]
2                                   [Sam Mendes]
3                            [Christopher Nolan]
4                               [Andrew Stanton]
                          ...
4804                          [Robert Rodriguez]
4805                              [Edward Burns]
4806                               [Scott Smith]
4807                               [Daniel Hsia]
4808    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: crew, Length: 4809, dtype: object

In [24]:
movies["genres"]=movies['genres'].apply(str_list)
movies["keywords"]=movies['keywords'].apply(str_list)

In [25]:
movies.isna().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [26]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
769,60000000,"[Family, Animation, Adventure]",http://sinbad-themovie.com/main.html,14411,"[prince, water monster]",en,Sinbad: Legend of the Seven Seas,The sailor of legend is framed by the goddess ...,18.815442,"[{""name"": ""DreamWorks Animation"", ""id"": 521}]",...,86.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,Sinbad: Legend of the Seven Seas,6.6,372,14411,"[Brad Pitt, Catherine Zeta-Jones, Michelle Pfe...","[Tim Johnson, Patrick Gilmore]"
4714,0,"[Action, Drama]",NaN,354624,[bmx],en,Heroes of Dirt,"Passionate BMX dirt jumper, Phin Cooper, wants...",0.076647,"[{""name"": ""Blue Trail Entertainment"", ""id"": 72...",...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Heroes of Dirt,0.0,0,354624,"[Joel Moody, William Martinez, Vivienne VanHorn]",[Eric Bugbee]
600,66000000,"[Action, Adventure, Thriller]",NaN,49021,[rescue],en,Killer Elite,"Based on a shocking true story, Killer Elite p...",29.501489,"[{""name"": ""Current Entertainment"", ""id"": 972},...",...,116.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,May the best man live.,Killer Elite,6.1,695,49021,"[Jason Statham, Clive Owen, Robert De Niro, Do...",[Gary McKendry]
1770,25000000,"[Adventure, Family, Fantasy]",http://movies.disney.com/return-to-oz,13155,[wizard of oz],en,Return to Oz,"Dorothy, saved from a psychiatric experiment b...",5.650125,"[{""name"": ""Silver Screen Partners II"", ""id"": 1...",...,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,An all-new adventure down the yellow brick road.,Return to Oz,6.7,120,13155,"[Fairuza Balk, Nicol Williamson, Jean Marsh, P...",[Walter Murch]
1363,35000000,"[Fantasy, Action]",NaN,268,"[double life, dc comics, dual identity, chemic...",en,Batman,The Dark Knight of Gotham City begins his war ...,44.104469,"[{""name"": ""PolyGram Filmed Entertainment"", ""id...",...,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Have you ever danced with the devil in the pal...,Batman,7.0,2096,2661,"[Adam West, Burt Ward, Lee Meriwether, Cesar R...",[Leslie H. Martinson]

In [27]:
# removing space
def _join(x):
  l=[]
  for i in x:
    l.append(i.replace(" ",""))
  return l

In [28]:
movies["cast"]=movies["cast"].apply(_join)

In [29]:
movies["cast"]=movies["cast"].apply(lambda i:i[0:3])

In [30]:
movies["cast"]

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4809, dtype: object

In [31]:
new_df=pd.DataFrame(movies,columns=['id','homepage','title','cast','crew','overview','genres','keywords'])

In [32]:

new_df.head(5)

,id,homepage,title,cast,crew,overview,genres,keywords
0,19995,http://www.avatarmovie.com/,Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,http://disney.go.com/disneypictures/pirates/,Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,http://www.sonypictures.com/movies/spectre/,Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[Sam Mendes],A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,http://www.thedarkknightrises.com/,The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan],Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,http://movies.disney.com/john-carter,John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton],"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [33]:
new_df['crew']=new_df['crew'].apply(_join)

In [34]:

new_df.head()

,id,homepage,title,cast,crew,overview,genres,keywords
0,19995,http://www.avatarmovie.com/,Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,285,http://disney.go.com/disneypictures/pirates/,Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,206647,http://www.sonypictures.com/movies/spectre/,Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,49026,http://www.thedarkknightrises.com/,The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,49529,http://movies.disney.com/john-carter,John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [35]:
new_df.isna().sum()

id             0
homepage    3096
title          0
cast           0
crew           0
overview       3
genres         0
keywords       0
dtype: int64

In [36]:

new_df["homepage"]=new_df["homepage"].fillna(0)

In [37]:
url=list(enumerate(new_df["homepage"]))
new_df["urls"]=0
for i in range(len(url)):
  if new_df["homepage"][i]==0:

    x=("{}/{}".format("https://www.",str("".join(list(new_df["title"][url[i][0]].split())))))

    new_df["urls"][i]=x
  else:
    new_df["urls"][i]=new_df["homepage"][i]

<ipython-input-37-873e8c635340>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["urls"][i]=new_df["homepage"][i]

In [38]:


# def link(url,i):
#   s=url
#   x="{} + {}".format("https://www.",str(new_df.iloc[[url[i][0]]].title))
#   iF s is "link"
#     return x
#   else:
#     return s
# # new_df[new_df["homepage"].fillna("{} + {}".format("https://www.",new_df["title"]]))
new_df["urls"]

0                             http://www.avatarmovie.com/
1            http://disney.go.com/disneypictures/pirates/
2             http://www.sonypictures.com/movies/spectre/
3                      http://www.thedarkknightrises.com/
4                    http://movies.disney.com/john-carter
                              ...
4804                              https://www./ElMariachi
4805                               https://www./Newlyweds
4806    http://www.hallmarkchannel.com/signedsealeddel...
4807                          http://shanghaicalling.com/
4808                          https://www./MyDatewithDrew
Name: urls, Length: 4809, dtype: object

In [39]:
# new_df.iloc[[0]].title
new_df.sample(5)

,id,homepage,title,cast,crew,overview,genres,keywords,urls
2040,146239,0,Delivery Man,"[VinceVaughn, CobieSmulders, ChrisPratt]",[KenScott],An affable underachiever finds out he's father...,[Comedy],"[remake, sperm donor]",https://www./DeliveryMan
2546,287903,http://www.krampusthefilm.com/,Krampus,"[AdamScott, ToniCollette, AllisonTolman]",[MichaelDougherty],A horror comedy based on the ancient legend ab...,"[Horror, Comedy, Fantasy]","[fire, winter, santa claus, snow storm, christ...",http://www.krampusthefilm.com/
2346,43959,http://www.soulsurferthemovie.com/,Soul Surfer,"[AnnaSophiaRobb, HelenHunt, LorraineNicholson]",[SeanMcNamara],Soul Surfer is the inspiring true story of tee...,"[Action, Drama]","[competition, based on novel, shark attack, su...",http://www.soulsurferthemovie.com/
2558,228970,http://howwilditwas.com/,Wild,"[ReeseWitherspoon, LauraDern, ThomasSadoski]",[Jean-MarcVallée],A woman with a tragic past decides to start he...,[Drama],"[adventure, biography, hiking, based on true s...",http://howwilditwas.com/
718,8914,0,Deep Blue Sea,"[ThomasJane, SaffronBurrows, LLCoolJ]",[RennyHarlin],On a remote former submarine refueling facilit...,"[Action, Science Fiction, Thriller]","[shark attack, shark, alzheimer's disease, kil...",https://www./DeepBlueSea

In [40]:
# to convert string into list of strings
def spliting(text):
  text=str(text).split()
  return text

In [41]:

new_df['overview']=new_df['overview'].apply(spliting)

In [42]:

new_df['all_tags']=new_df['overview'] + new_df['genres'] + new_df['keywords'] + new_df['cast'] + new_df['crew']

In [43]:

new_df.drop(columns=['overview','genres' ,'keywords','cast' , 'crew','homepage'],inplace=True)

In [44]:

new_df.head()

,id,title,urls,all_tags
0,19995,Avatar,http://www.avatarmovie.com/,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,http://movies.disney.com/john-carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [45]:

#converting all tags in lower case and deletion similarities

In [46]:
def convert_lower(text):
  l=[]
  for item in text:
    l.append(item.lower())
  return l

In [47]:
new_df['all_tags']=new_df['all_tags'].apply(convert_lower)

In [48]:

new_df.head()

,id,title,urls,all_tags
0,19995,Avatar,http://www.avatarmovie.com/,"[in, the, 22nd, century,, a, paraplegic, marin..."
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,"[captain, barbossa,, long, believed, to, be, d..."
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,"[a, cryptic, message, from, bond’s, past, send..."
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,"[following, the, death, of, district, attorney..."
4,49529,John Carter,http://movies.disney.com/john-carter,"[john, carter, is, a, war-weary,, former, mili..."

In [49]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)

In [50]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def steming(text):
  l=[]
  for i in text:

    l.append(ps.stem(i))
  return l

In [51]:
new_df['all_tags']=new_df['all_tags'].apply(steming)

In [52]:
new_df.sample(5)

,id,title,urls,all_tags
3482,67913,The Guard,http://www.sonyclassics.com/theguard,"[two, policemen, must, join, forc, to, take, o..."
2240,48231,A Dangerous Method,http://www.sonyclassics.com/adangerousmethod/,"[seduc, by, the, challeng, of, an, imposs, cas..."
4145,115210,Stitches,https://www./Stitches,"[the, clumsi, and, unfunni, clown, richard, ""s..."
3984,55831,Boynton Beach Club,https://www./BoyntonBeachClub,"[a, hand, of, men, and, women, of, a, certain,..."
3037,14729,The Long Riders,https://www./TheLongRiders,"[the, origins,, exploit, and, the, ultim, fate..."

In [53]:
new_df["all_tags"]=new_df["all_tags"].apply(_join)

In [54]:
new_df['all_tags'] = new_df['all_tags'].apply(lambda x: " ".join(x))

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')

In [56]:
data = cv.fit_transform(new_df['all_tags']).toarray()
data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(data)
similarity

array([[1.        , 0.06776309, 0.06862635, ..., 0.03571429, 0.        ,
        0.        ],
       [0.06776309, 1.        , 0.05063697, ..., 0.01976424, 0.        ,
        0.0209427 ],
       [0.06862635, 0.05063697, 1.        , ..., 0.02001602, 0.        ,
        0.        ],
       ...,
       [0.03571429, 0.01976424, 0.02001602, ..., 1.        , 0.03311331,
        0.03311331],
       [0.        , 0.        , 0.        , ..., 0.03311331, 1.        ,
        0.07017544],
       [0.        , 0.0209427 , 0.        , ..., 0.03311331, 0.07017544,
        1.        ]])

In [58]:
def movie_recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:8]:


      print("{} {}".format(new_df.iloc[i[0]].title,new_df.iloc[i[0]].urls))

In [59]:
movie_recommend("Avatar")

Aliens https://www./Aliens
Aliens vs Predator: Requiem http://www.avp-r.com/
Titan A.E. https://www./TitanA.E.
Independence Day https://www./IndependenceDay
Battle: Los Angeles http://www.battlela.com
Meet Dave http://www.meetdavemovie.com/
Predators https://www./Predators

In [60]:
movie_recommend("Batman")

Batman https://www./Batman
Batman & Robin https://www./Batman&Robin
The R.M. http://www.halestormentertainment.com/p_movies_details.asp?mID=jnlppmp8
Batman Begins http://www2.warnerbros.com/batmanbegins/index.html
Batman Returns https://www./BatmanReturns
The Dark Knight http://thedarkknight.warnerbros.com/dvdsite/
The Dark Knight Rises http://www.thedarkknightrises.com/

In [61]:
movie_recommend("2016: Obama's America")

Captain America: The Winter Soldier http://www.captainamericathewintersoldiermovie.com
Bowling for Columbine http://www.bowlingforcolumbine.com/index.php
Captain America: The First Avenger http://captainamerica.marvel.com/
The Algerian http://thealgerianmovie.com/
Team America: World Police http://www.teamamerica.com
Beavis and Butt-Head Do America https://www./BeavisandButt-HeadDoAmerica
Nothing But a Man https://www./NothingButaMan

In [62]:
movie_recommend("Iron Man")

Iron Man 3 http://marvel.com/ironman3
Iron Man 2 http://www.ironmanmovie.com/
Avengers: Age of Ultron http://marvel.com/movies/movie/193/avengers_age_of_ultron
The Avengers http://marvel.com/avengers_movie/
Captain America: Civil War http://marvel.com/captainamericapremiere
X-Men https://www./X-Men
X-Men Origins: Wolverine http://www.x-menorigins.com/

In [63]:
import pickle

In [64]:

pickle.dump(new_df,open("movie_recm.pkl","wb"))
pickle.dump(similarity,open("similarity.pkl","wb"))

In [65]:

np.array(new_df["title"])

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [66]:
#!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-6.0.0.tar.gz (681 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 681.2/681.2 kB 10.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyngrok) (6.0)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19867 sha256=cb5a975cb3c619cc9ff98802bad5379db3e88ec55bfbb07431711027b2c20d55
  Stored in directory: /root/.cache/pip/wheels/5c/42/78/0c3d438d7f5730451a25f7ac6cbf4391759d22a67576ed7c2c
Successfully built pyngrok
Installing collected packages: pyngrok
Successfully installed pyngrok-6.0.0

In [67]:
#!streamlit run app.py & npx localtunnel --port[80]

Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py
npx: installed 22 in 6.09s
Usage: lt --port [num] <options>

Options:
  -p, --port                Internal HTTP server port                 [required]
  -h, --host                Upstream server providing forwarding
                                             [default: "https://localtunnel.me"]
  -s, --subdomain           Request this subdomain
  -l, --local-host          Tunnel traffic to this host instead of localhost,
                            override Host header to this host
      --local-https         Tunnel traffic to a local HTTPS server     [boolean]
      --local-cert          Path to certificate PEM file for local HTTPS server
      --local-key           Path to certificate key file for local HTTPS server
      --local-ca            Path to certificate authority file for self-signed
                            certificates
      --allow-invalid-cert  Disable certificate checks for your local HTTPS
                            server (ignore cert/key/ca options)        [boolean]
  -o, --open                Opens the tunnel URL in your browser
      --print-requests      Print basic request info                   [boolean]
      --help                Show this help and exit                    [boolean]
      --version             Show version number                        [boolean]

Missing required argument: port

2023-07-01 15:44:14.924
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run app.py [ARGUMENTS]